name: mapquantassemble
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bedtools =2.28.0
  - biopython =1.73
  - cufflinks =2.2.1
  - cutadapt =2.1
  - drmaa =0.7.9
  - pandas =0.23
  - perl =5.26.2
  - python =3.6
  - snakemake-minimal =5.5.0
  - STAR =2.7.2a
